---
- name: Manage primary named.conf
  template:
    src: named.conf.j2
    dest: "{{ named_conf }}"
    owner:  root
    group:  root
    mode:   '0750'
    backup: yes # TODO: change to no after role dev done
